name: docs.extrapolations.dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip

  - pip:
      # Base Python deps
      - setuptools
      - setuptools-scm
      - pylint
      - flake8
      - black
      - isort
      - twine
      - wheel
      - pytest
      - pytest-cov

      # Docs
      - mkdocs
      - mkdocs-material==7.1.0
      - mkdocs-jupyter>=0.16.1
      - mkdocs-minify-plugin
      - pygments
      - pymdown-extensions
