site_name: Inmatura AWS Docs
site_url: https://aws.inmatura.com
site_author: Inmatura LLC
site_description: >-
  Documentation for Inmatura AWS offerings
copyright: Copyright &copy; 2019 - 2023 Inmatura LLC
nav:
  - Home: index.md
  - JupyterHub AMI:
      - Overview: ami/jupyterhub/index.md
      - Launch in EC2: ami/jupyterhub/launch-ec2.md
      - User management: ami/jupyterhub/user-mgmt.md
      - Server Management: ami/jupyterhub/server-mgmt.md
      - Custom Domain: ami/jupyterhub/custom-domain.md
      - HTTPS: ami/jupyterhub/https.md
      - Support: ami/jupyterhub/support.md
      - Terminating: ami/jupyterhub/terminate.md
      - IDEs:
          - Jupyter: ami/jupyterhub/ide/jupyter.md
          - RStudio: ami/jupyterhub/ide/rstudio.md
          - VS Code: ami/jupyterhub/ide/vscode.md
      - Languages:
          - Python: ami/jupyterhub/lang/python.md
          - R: ami/jupyterhub/lang/r.md
      - Libraries:
          - PyTorch and Tensorflow: ami/jupyterhub/library/pytorch-and-tf.md
          - RAPIDS: ami/jupyterhub/library/rapids.md
          - GPU: ami/jupyterhub/library/gpu.md
          - Dask: ami/jupyterhub/library/dask.md
          - Voila: ami/jupyterhub/library/voila.md
          - Versions: ami/jupyterhub/library/versions.md
  - Instance Segmentation Mask R-CNN:
      - Overview: model/instance-segmentation-mask-r-cnn/index.md
      - Launch Model Endpoint: model/instance-segmentation-mask-r-cnn/launch-endpoint.md
      - API: model/instance-segmentation-mask-r-cnn/api.md
      - Examples: model/instance-segmentation-mask-r-cnn/examples.md
      - Performance: model/instance-segmentation-mask-r-cnn/performance.md
      - Terminating: model/instance-segmentation-mask-r-cnn/terminate.md

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        name: Switch to light mode
        icon: material/brightness-7
    # Palette toggle for dark mode
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        name: Switch to dark mode
        icon: material/brightness-3

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/medium-zoom.min.js
  - assets/js/custom.js

extra:
  generator: false
  analytics:
    provider: google
    property: G-X2LE8JXLW3
