site_name: Extrapolations Docs
site_url: https://docs.extrapolations.dev
copyright: Copyright 2019 - 2021 Daniel Rodriguez

nav:
  - Home: index.md
  - JupyterHub AMI:
    - Overview: jupyterhub-ami/index.md
    - Launch in EC2: jupyterhub-ami/launch-ec2.md
    - IDEs: jupyterhub-ami/ides.md
    - User management: jupyterhub-ami/user-mgmt.md
    - Configuration: jupyterhub-ami/configuration.md
    - GPU: jupyterhub-ami/gpu.md
    - Packages: jupyterhub-ami/packages.md
    - Libraries:
      - Dask: jupyterhub-ami/dask.md
      - Voila: jupyterhub-ami/voila.md
    - Terminating: jupyterhub-ami/terminate.md
  - GPT-2:
    - Overview: models/gpt-2/index.md
    - Launch in SageMaker: models/gpt-2/launch.md
    - API: models/gpt-2/api.md
    - Examples: models/gpt-2/examples.md
    - Performance: models/gpt-2/performance.md
    - Terminating: models/gpt-2/terminate.md
  - EfficientNet-B3:
    - Overview: models/efficientnet-b3/index.md
    - Train an Algorithm in SageMaker: models/efficientnet-b3/train.md
    - Launch Endpoint - Custom model: models/efficientnet-b3/train-endpoint.md
    - Launch Endpoint - Base model: models/efficientnet-b3/base-endpoint.md
    - API: models/efficientnet-b3/api.md
    - Examples: models/efficientnet-b3/examples.md
    - Terminating: models/efficientnet-b3/terminate.md
  - Object Detection Mask R-CNN:
    - Overview: models/img-obj-mask-r-cnn/index.md
    - Launch Endpoint: models/img-obj-mask-r-cnn/launch-endpoint.md
    - API: models/img-obj-mask-r-cnn/api.md
    - Examples: models/img-obj-mask-r-cnn/examples.md
    - Performance: models/img-obj-mask-r-cnn/performance.md
    - Terminating: models/img-obj-mask-r-cnn/terminate.md

theme:
  name: material
  custom_dir: docs/theme
  favicon: assets/img/favicon.png
  logo: assets/img/logo.png

  features:
    - navigation.tabs
    - navigation.sections

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/medium-zoom.min.js
  - assets/js/custom.js

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - attr_list
  - meta
  - pymdownx.tabbed
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

google_analytics:
  - "UA-35523657-8"
  - "auto"
