site_name: Extrapolations Docs
site_url: https://docs.extrapolations.dev
site_author: Daniel Rodriguez
site_description: >-
  Documentation for Extrapolations.dev AWS offerings
copyright: Copyright &copy; 2019 - 2023 Daniel Rodriguez
nav:
  - Home: index.md
  - JupyterHub AMI:
      - Overview: ami/jupyterhub/index.md
      - Launch in EC2: ami/jupyterhub/launch-ec2.md
      - User management: ami/jupyterhub/user-mgmt.md
      - Server Management: ami/jupyterhub/management.md
      - Custom DNS: ami/jupyterhub/dns.md
      - SSL: ami/jupyterhub/ssl.md
      - Support: ami/jupyterhub/support.md
      - Terminating: ami/jupyterhub/terminate.md
      - IDEs:
          - Jupyter: ami/jupyterhub/jupyter.md
          - RStudio: ami/jupyterhub/rstudio.md
          - VS Code: ami/jupyterhub/vscode.md
      - Languages:
          - Python: ami/jupyterhub/python.md
          - R: ami/jupyterhub/r.md
      - Libraries:
          - Tensorflow/PyTorch: ami/jupyterhub/tf-th.md
          - RAPIDS: ami/jupyterhub/rapids.md
          - GPU: ami/jupyterhub/gpu.md
          - Dask: ami/jupyterhub/dask.md
          - Voila: ami/jupyterhub/voila.md
          - Other versions: ami/jupyterhub/versions.md
  - Instance Segmentation Mask R-CNN:
      - Overview: model/instance-segmentation-mask-r-cnn/index.md
      - Launch Model Endpoint: model/instance-segmentation-mask-r-cnn/launch-endpoint.md
      - API: model/instance-segmentation-mask-r-cnn/api.md
      - Examples: model/instance-segmentation-mask-r-cnn/examples.md
      - Performance: model/instance-segmentation-mask-r-cnn/performance.md
      - Terminating: model/instance-segmentation-mask-r-cnn/terminate.md

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/medium-zoom.min.js
  - assets/js/custom.js

extra:
  generator: false
  analytics:
    provider: google
    property: G-X2LE8JXLW3
