version: "3"

tasks:
  build:
    cmds:
      - mkdocs build

  lockfiles:
    cmds:
      - pip-compile -q --resolver=backtracking -o requirements.txt pyproject.toml

  serve:
    cmds:
      - mkdocs serve
