name: deploy

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-env: true

      - name: Print Python versions
        run: |
          source .venv/bin/activate
          which python
          which pip
          python --version
          pip --version

      - name: Build docs
        run: |
          source .venv/bin/activate
          task build

      # ------------------------------------------------------------------------
      # Release

      - name: Preview - Upload to Netlify
        if: github.event_name == 'pull_request'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Prod - Upload to Netlify
        if: (github.event_name != 'pull_request') && endsWith(github.ref, '/main')
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=site --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
