name: deploy

concurrency:
  group: deploy-gcs
  cancel-in-progress: true

on:
  workflow_call:
    secrets:
      GCP_SERVICE_ACCOUNT:
        required: true
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_BUCKET:
        required: true

jobs:
  prod:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Restore built website
        uses: actions/cache@v3
        with:
          path: dist
          key: >
            dist
            ${{ github.run_id }}
            ${{ github.run_attempt }}
          fail-on-cache-miss: true

      - name: Configure GCP auth
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: dist
          destination: ${{ secrets.GCP_BUCKET_PROD }}
          parent: false
          headers: |-
            cache-control: no-cache

      - name: Upload to GCS (sync)
        run: gsutil -m rsync -r -d dist gs://${{ secrets.GCP_BUCKET_PROD }}

      - name: Configure GSC Cache
        run: |
          gsutil -m setmeta -r -h "Cache-Control: no-cache" gs://${{ secrets.GCP_BUCKET_PROD }}
